targets:
  $default:
    builders:
      plex:
        enabled: true

builders:
  plex:
    import: "package:plex/plex_annotations/plex_annotation_builders/plex_annotation_builders.dart"
    builder_factories: ["generateModel"]
    build_extensions: { ".dart": [".plex.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]