name: plex
description: PLEX is Flutter UI framework for enterprise apps with pre-built components and best practices for efficient development in addition with many built in widgets

version: 0.2.7
homepage: https://github.com/rehmnabdul/plex

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Navigation
  get: ^4.6.5

  #Storage
  shared_preferences: ^2.2.1

  #Networking
  http: ^1.1.0

  #Utils
  intl: ^0.18.1

  #Print Excel File
  syncfusion_flutter_xlsio: ^23.1.39
  file_saver: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2