name: plex
description: PLEX is Flutter UI framework for enterprise apps with pre-built components and best practices for efficient development in addition with many built in widgets

version: 0.8.4
homepage: https://github.com/rehmnabdul/plex

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

  #Connectivity
  connectivity_plus: ^6.1.1

  #Navigation
  get: ^4.6.6

  # Messages
  toastification: ^2.3.0

  #Path
  path_provider: ^2.1.5

  #Storage
  shared_preferences: ^2.3.4

  #Networking
  http: ^1.2.2
  cached_network_image: ^3.4.1

  #Utils
  intl: ^0.19.0

  #Animations
  flutter_animate: ^4.5.2

  #Table
  syncfusion_flutter_core: ^28.1.36
  syncfusion_flutter_datagrid: ^28.1.36
  syncfusion_flutter_datagrid_export: ^28.1.36

  #Print Excel File
  syncfusion_flutter_xlsio: ^28.1.36
  file_saver: ^0.2.14

  #Code Builder
  #  build: ^2.4.2
  #  source_gen: ^2.0.0
  #  analyzer: ^6.11.0

  #Database
  sembast: ^3.8.0+1

  #Lootie Animation
  lottie: ^3.3.0

  #SignalR
  #  signalr_netcore: ^0.1.7+1
  signalr_netcore: ^1.4.0

  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_lints: ^5.0.0
#  build_runner: ^2.4.14

flutter:
  assets:
    - packages/plex/assets/excel.png
    - packages/plex/assets/pdf.png
    - packages/plex/assets/group_data.png
    - packages/plex/assets/loading/loading_1.json
    - packages/plex/assets/loading/loading_2.json