name: plex
description: PLEX is Flutter UI framework for enterprise apps with pre-built components and best practices for efficient development in addition with many built in widgets

version: 0.6.3
homepage: https://github.com/rehmnabdul/plex

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

  #Connectivity
  connectivity_plus: ^6.0.4

  #Navigation
  get: ^4.6.6

  # Messages
  toastification: ^2.1.0

  #Path
  path_provider: ^2.1.3

  #Storage
  shared_preferences: ^2.2.3

  #Networking
  http: ^1.2.2
  cached_network_image: ^3.3.1

  #Utils
  intl: ^0.19.0

  #Animations
  flutter_animate: ^4.5.0

  #Table
  syncfusion_flutter_core: ^26.2.7
  syncfusion_flutter_datagrid: ^26.2.7
  syncfusion_flutter_datagrid_export: ^26.2.7

  #Print Excel File
  syncfusion_flutter_xlsio: ^26.2.7
  file_saver: ^0.2.13

  #Code Builder
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1

  #Database
  sembast: ^3.7.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:

  assets:
    - packages/plex/assets/excel.png
    - packages/plex/assets/pdf.png
    - packages/plex/assets/group_data.png